/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.bg.ac.fon.ps.forms;

import javax.swing.JOptionPane;
import rs.bg.ac.fon.ps.communication.Response;
import rs.bg.ac.fon.ps.controler.Controller;
import rs.bg.ac.fon.ps.domain.dto.StatisticsDto;
import rs.bg.ac.fon.ps.domain.impl.Supervisor;

/**
 *
 * @author nikola.dulovic
 */
public class MainForm extends javax.swing.JFrame {

    private final Supervisor currentSupervisor;

    public MainForm(Supervisor supervisor) {
        initComponents();
        currentSupervisor = supervisor;
        setLocationRelativeTo(null);
        lblCurrentUser.setText(currentSupervisor.getUsername());
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        lblCurrentUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPutnikNumber = new javax.swing.JLabel();
        lblLetNumber = new javax.swing.JLabel();
        lblLinesNumber = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnPassenger = new javax.swing.JMenu();
        miAddPassenger = new javax.swing.JMenuItem();
        miSearchPassenger = new javax.swing.JMenuItem();
        mnFlight = new javax.swing.JMenu();
        miAddFlight = new javax.swing.JMenuItem();
        miSearchFlights = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Početna stranica");

        jLabel1.setText("Ulogovani korisnik:");

        btnLogout.setText("Odjavi se");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setText("Dobrodošli na početnu stranicu");

        jLabel3.setText("Ukupan broj putnika:");

        jLabel4.setText("Ukupan broj  realizovanih letova:");

        jLabel5.setText("Ukupan broj realizovanih avio linija:");

        mnPassenger.setText("Putnik");

        miAddPassenger.setText("Dodaj novog");
        miAddPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddPassengerActionPerformed(evt);
            }
        });
        mnPassenger.add(miAddPassenger);

        miSearchPassenger.setText("Pretraži");
        miSearchPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSearchPassengerActionPerformed(evt);
            }
        });
        mnPassenger.add(miSearchPassenger);

        jMenuBar1.add(mnPassenger);

        mnFlight.setText("Let");

        miAddFlight.setText("Dodaj novi");
        miAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddFlightActionPerformed(evt);
            }
        });
        mnFlight.add(miAddFlight);

        miSearchFlights.setText("Pretraži");
        miSearchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSearchFlightsActionPerformed(evt);
            }
        });
        mnFlight.add(miSearchFlights);

        jMenuBar1.add(mnFlight);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLinesNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(lblLetNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPutnikNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPutnikNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblLetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblLinesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblCurrentUser))
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAddPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddPassengerActionPerformed
        new ZapamtiPutnikaForm(this, true).setVisible(true);
    }//GEN-LAST:event_miAddPassengerActionPerformed

    private void miSearchPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSearchPassengerActionPerformed
        new PretraziPutnikeForm(this, true).setVisible(true);
    }//GEN-LAST:event_miSearchPassengerActionPerformed

    private void miAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddFlightActionPerformed
        new ZapamtiLetForm(this, true).setVisible(true);
    }//GEN-LAST:event_miAddFlightActionPerformed

    private void miSearchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSearchFlightsActionPerformed
        new PretraziLetoveForm(this, true).setVisible(true);
    }//GEN-LAST:event_miSearchFlightsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da se izlogujete?", "Potvrdite izbor", JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JLabel lblLetNumber;
    private javax.swing.JLabel lblLinesNumber;
    private javax.swing.JLabel lblPutnikNumber;
    private javax.swing.JMenuItem miAddFlight;
    private javax.swing.JMenuItem miAddPassenger;
    private javax.swing.JMenuItem miSearchFlights;
    private javax.swing.JMenuItem miSearchPassenger;
    private javax.swing.JMenu mnFlight;
    private javax.swing.JMenu mnPassenger;
    // End of variables declaration//GEN-END:variables

    private void init() {
        try {
            Response res = Controller.getInstance().getStatistics();

            if (res.getException() == null) {
                StatisticsDto stats = (StatisticsDto) res.getResponseObj();
                lblPutnikNumber.setText(String.valueOf(stats.getStatistics()[0]));
                lblLetNumber.setText(String.valueOf(stats.getStatistics()[1]));
                lblLinesNumber.setText(String.valueOf(stats.getStatistics()[2]));
            }

        } catch (Exception e) {
            lblLetNumber.setText("Trenutno nema registrovanih letova");
            lblLinesNumber.setText("Trenutno nema registrovanih avio linija");
            lblPutnikNumber.setText("Trenutno nema registrovanih putnika");
        }

    }
}
