/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.bg.ac.fon.ps.forms;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import rs.bg.ac.fon.ps.communication.Response;
import rs.bg.ac.fon.ps.controler.Controller;
import rs.bg.ac.fon.ps.domain.impl.AvioLinija;
import rs.bg.ac.fon.ps.domain.GenericEntity;
import rs.bg.ac.fon.ps.domain.impl.Let;
import rs.bg.ac.fon.ps.table.LetTableModel;

/**
 *
 * @author nikola.dulovic
 */
public class PretraziLetoveForm extends javax.swing.JDialog {

    private LetTableModel flightTableModel;
    private Let selectedFlight;
    private static final String NEPOTPUNO = "Nepotpuni podaci";
    private static final String TIME_FORMAT = "yyyy.MM.dd HH:mm:ss";

    public PretraziLetoveForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbSearchCriteria = new javax.swing.JComboBox<>();
        btnApply = new javax.swing.JButton();
        pnlLines = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbLines = new javax.swing.JComboBox<>();
        btnSearchLine = new javax.swing.JButton();
        pnlDate = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDateFrom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDateTo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSearchByDates = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnLoadFlight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga letova");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kriterijum"));

        jLabel1.setText("Odaberite kriterijum pretrage:");

        cbSearchCriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Po avio liniji", "Po datumu polaska" }));

        btnApply.setText("Primeni");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSearchCriteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApply)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbSearchCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApply)
                .addGap(15, 15, 15))
        );

        pnlLines.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga po avio liniji"));

        jLabel2.setText("Odaberite avio liniju:");

        cbLines.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLinesActionPerformed(evt);
            }
        });

        btnSearchLine.setText("Pretraži");
        btnSearchLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLinesLayout = new javax.swing.GroupLayout(pnlLines);
        pnlLines.setLayout(pnlLinesLayout);
        pnlLinesLayout.setHorizontalGroup(
            pnlLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLinesLayout.createSequentialGroup()
                .addGroup(pnlLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLinesLayout.createSequentialGroup()
                        .addGroup(pnlLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLinesLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel2))
                            .addGroup(pnlLinesLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(cbLines, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLinesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearchLine)))
                .addContainerGap())
        );
        pnlLinesLayout.setVerticalGroup(
            pnlLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLinesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchLine)
                .addGap(16, 16, 16))
        );

        pnlDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga po vremenu polaska"));

        jLabel3.setText("Vreme polaska od:");

        jLabel4.setText("do:");

        jLabel5.setText("Koristiti format yyyy.mm.dd hh:mm:ss");

        btnSearchByDates.setText("Pretraži");
        btnSearchByDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByDatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDateLayout = new javax.swing.GroupLayout(pnlDate);
        pnlDate.setLayout(pnlDateLayout);
        pnlDateLayout.setHorizontalGroup(
            pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(42, 42, 42))
            .addGroup(pnlDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearchByDates))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDateLayout.setVerticalGroup(
            pnlDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchByDates)
                .addGap(15, 15, 15))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezultati pretrage"));

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFlights);

        btnCancel.setText("Izađi");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnLoadFlight.setText("Učitaj");
        btnLoadFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLoadFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLoadFlight)
                            .addComponent(btnCancel))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlLines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed

        btnLoadFlight.setEnabled(false);

        if (cbSearchCriteria.getSelectedIndex() == 0) {
            populateCbLines();
            cbLines.setEnabled(true);
            btnSearchLine.setEnabled(true);
            btnSearchByDates.setEnabled(false);
            txtDateFrom.setEnabled(false);
            txtDateTo.setEnabled(false);

        } else {
            cbLines.setEnabled(false);
            btnSearchLine.setEnabled(false);
            btnSearchByDates.setEnabled(true);
            txtDateFrom.setEnabled(true);
            txtDateTo.setEnabled(true);
        }
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnSearchByDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByDatesActionPerformed
        datesCriteriaSelected();
    }//GEN-LAST:event_btnSearchByDatesActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da napustite stranicu?", "Potvrdite izbor", JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLinesActionPerformed

    private void btnLoadFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFlightActionPerformed
        btnLoadFlight.setEnabled(false);
        IzmeniLetForm ipf = new IzmeniLetForm(this, true, selectedFlight, flightTableModel);
        ipf.setVisible(true);
    }//GEN-LAST:event_btnLoadFlightActionPerformed

    private void btnSearchLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLineActionPerformed
        cbAvioLinijeItemSelected();
    }//GEN-LAST:event_btnSearchLineActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoadFlight;
    private javax.swing.JButton btnSearchByDates;
    private javax.swing.JButton btnSearchLine;
    private javax.swing.JComboBox<Object> cbLines;
    private javax.swing.JComboBox<String> cbSearchCriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDate;
    private javax.swing.JPanel pnlLines;
    private javax.swing.JTable tblFlights;
    private javax.swing.JTextField txtDateFrom;
    private javax.swing.JTextField txtDateTo;
    // End of variables declaration//GEN-END:variables

    private void init() {        
        btnLoadFlight.setEnabled(false);
        txtDateFrom.setEnabled(false);
        txtDateTo.setEnabled(false);
        btnSearchByDates.setEnabled(false);
        btnSearchLine.setEnabled(false);
        cbLines.setEnabled(false);

        LinkedList<Let> flights = new LinkedList<>();

        flightTableModel = new LetTableModel(flights);
        tblFlights.setModel(flightTableModel);

        tblFlights.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    btnLoadFlight.setEnabled(true);
                    selectedFlight = (Let) flightTableModel.getValueAtRow(row);
                }
            }

        });
    }

    private void populateCbLines() {
        try {
            List<AvioLinija> lines = Controller.getInstance().getLinesList();

            cbLines.removeAllItems();
            lines.forEach((line) -> {
                cbLines.addItem(line);
            });

        } catch (Exception ex) {
            Logger.getLogger(PretraziLetoveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cbAvioLinijeItemSelected() {
        try {
            AvioLinija line = (AvioLinija) cbLines.getSelectedItem();
            LinkedList<GenericEntity> flights = new LinkedList<>();
            Response res = Controller.getInstance().searchFlightsByLines(line.getId().toString(), flights);

            populateFlightsTable(res);

        } catch (Exception ex) {
            Logger.getLogger(PretraziLetoveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void datesCriteriaSelected() {
        try {
            Date dateFrom;
            Date dateTo;

            try {
                String dateFromStr = this.txtDateFrom.getText();
                dateFrom = new SimpleDateFormat(TIME_FORMAT).parse(dateFromStr);
            } catch (ParseException pe) {
                JOptionPane.showMessageDialog(this, "Vreme polaska mora biti u formatu " + TIME_FORMAT + "!", NEPOTPUNO, JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                String dateToStr = this.txtDateTo.getText();
                dateTo = new SimpleDateFormat(TIME_FORMAT).parse(dateToStr);
            } catch (ParseException pe) {
                JOptionPane.showMessageDialog(this, "Vreme dolaska mora biti u formatu " + TIME_FORMAT + "!", NEPOTPUNO, JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (dateFrom.after(dateTo)) {
                JOptionPane.showMessageDialog(this, "Vreme polaska mora biti pre vremena dolaska!", NEPOTPUNO, JOptionPane.WARNING_MESSAGE);
                return;
            }

            LinkedList<GenericEntity> flights = new LinkedList<>();
            Response res = Controller.getInstance().searchFlightsByStartDate(dateFrom, dateTo, flights);

            populateFlightsTable(res);

        } catch (Exception ex) {
            Logger.getLogger(PretraziLetoveForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void populateFlightsTable(Response res) {
        if (res.getException() == null) {
            btnLoadFlight.setEnabled(false);
            flightTableModel.deleteResults();

            List<Let> list1 = (List<Let>) res.getResponseObj();

            if (list1.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nisu pronađeni letovi na osnovu zadatog kriterijuma", "Nema rezultata", JOptionPane.INFORMATION_MESSAGE);
            } else {
                flightTableModel.setList(list1);
                JOptionPane.showMessageDialog(this, "Sistem je pronašao letove po zadatoj vrednosti", "Uspešno pretraživanje letova", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, res.getException().getMessage(), "Neuspešno pretraživanje letova", JOptionPane.ERROR_MESSAGE);
            flightTableModel.deleteResults();
        }
    }
}
